import { defaultSettings, KEYS, type SchoolSettings } from "@/lib/storage";
import logoImg from "@/assets/logo.png";

export function getSchoolSettings(): SchoolSettings {
  try {
    const raw = localStorage.getItem(KEYS.SETTINGS);
    if (!raw) return defaultSettings;
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed)) return parsed[0] || defaultSettings;
    return parsed;
  } catch {
    return defaultSettings;
  }
}

export function brandedPrintHeader(title?: string): string {
  const s = getSchoolSettings();
  return `
<div class="brand-header" style="display:flex; align-items:center; justify-content:space-between; border-bottom:3px solid #1B1464; padding-bottom:10px; margin-bottom:15px; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">
  <div style="display:flex; align-items:center; gap:15px;">
    <img src="${logoImg}" alt="Logo" style="width:75px; height:75px; border-radius:10px; object-fit:cover; border:2px solid #1B1464; padding:2px;" />
    <div style="text-align:left;">
      <h1 style="margin:0; font-size:22px; color:#1B1464; text-transform:uppercase; letter-spacing:1px;">${s.name || "Mujahideen Preparatory School"}</h1>
      <p style="margin:3px 0; font-size:11px; color:#D81B8C; font-weight:bold; font-style:italic;">"${s.motto || "God Fearing and Better Future Starts Here"}"</p>
      <p style="margin:1px 0; font-size:11px; color:#444;">${s.location || "Mankessim, Ghana"} | Tel: ${s.phone || "Contact School"}</p>
      <p style="margin:1px 0; font-size:11px; color:#444;">Email: ${s.email || "info@school.edu.gh"}</p>
    </div>
  </div>
  ${title ? `
  <div style="text-align:right;">
    <div style="background:#1B1464; color:white; padding:6px 15px; border-radius:4px; font-weight:bold; font-size:12px; display:inline-block; margin-bottom:8px;">${title}</div>
    <p style="margin:0; font-size:10px; color:#666;">ACADEMIC YEAR: ${s.academicYear || "2025/2026"}</p>
    <p style="margin:0; font-size:10px; color:#666;">TERM: ${s.currentTerm || "Current Term"}</p>
  </div>` : ""}
</div>`;
}

export function brandedPrintFooter(): string {
  const s = getSchoolSettings();
  return `
<div style="margin-top:40px; padding-top:15px; border-top:2px solid #eee; display:flex; justify-content:space-between; align-items:flex-end; font-family:'Segoe UI', Tahoma, sans-serif;">
  <div style="text-align:left;">
    <div style="width:180px; border-bottom:1px solid #333; margin-bottom:5px;"></div>
    <p style="margin:0; font-size:11px; color:#333; font-weight:bold;">HEADMASTER'S SIGNATURE</p>
  </div>
  <div style="text-align:right;">
    <p style="margin:0; font-size:10px; color:#999;">Generated by ${s.name} Management System</p>
    <p style="margin:0; font-size:10px; color:#999;">Date: ${new Date().toLocaleDateString("en-GB", { day: 'numeric', month: 'long', year: 'numeric' })}</p>
  </div>
</div>`;
}
