/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTimetableRouteImport } from './routes/_app.timetable'
import { Route as AppTeachersRouteImport } from './routes/_app.teachers'
import { Route as AppTeacherDashboardRouteImport } from './routes/_app.teacher-dashboard'
import { Route as AppSubjectsRouteImport } from './routes/_app.subjects'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResultsRouteImport } from './routes/_app.results'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppParentsRouteImport } from './routes/_app.parents'
import { Route as AppParentDashboardRouteImport } from './routes/_app.parent-dashboard'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppFeesRouteImport } from './routes/_app.fees'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCommunicationsRouteImport } from './routes/_app.communications'
import { Route as AppClassesRouteImport } from './routes/_app.classes'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'
import { Route as AppTeachersTeacherIdRouteImport } from './routes/_app.teachers.$teacherId'
import { Route as AppStudentsStudentIdRouteImport } from './routes/_app.students.$studentId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimetableRoute = AppTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherDashboardRoute = AppTeacherDashboardRouteImport.update({
  id: '/teacher-dashboard',
  path: '/teacher-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppParentsRoute = AppParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AppRoute,
} as any)
const AppParentDashboardRoute = AppParentDashboardRouteImport.update({
  id: '/parent-dashboard',
  path: '/parent-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppFeesRoute = AppFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunicationsRoute = AppCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersTeacherIdRoute = AppTeachersTeacherIdRouteImport.update({
  id: '/$teacherId',
  path: '/$teacherId',
  getParentRoute: () => AppTeachersRoute,
} as any)
const AppStudentsStudentIdRoute = AppStudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AppStudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/classes': typeof AppClassesRoute
  '/communications': typeof AppCommunicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/fees': typeof AppFeesRoute
  '/library': typeof AppLibraryRoute
  '/notifications': typeof AppNotificationsRoute
  '/parent-dashboard': typeof AppParentDashboardRoute
  '/parents': typeof AppParentsRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/subjects': typeof AppSubjectsRoute
  '/teacher-dashboard': typeof AppTeacherDashboardRoute
  '/teachers': typeof AppTeachersRouteWithChildren
  '/timetable': typeof AppTimetableRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
  '/teachers/$teacherId': typeof AppTeachersTeacherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/attendance': typeof AppAttendanceRoute
  '/calendar': typeof AppCalendarRoute
  '/classes': typeof AppClassesRoute
  '/communications': typeof AppCommunicationsRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/fees': typeof AppFeesRoute
  '/library': typeof AppLibraryRoute
  '/notifications': typeof AppNotificationsRoute
  '/parent-dashboard': typeof AppParentDashboardRoute
  '/parents': typeof AppParentsRoute
  '/reports': typeof AppReportsRoute
  '/results': typeof AppResultsRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRouteWithChildren
  '/subjects': typeof AppSubjectsRoute
  '/teacher-dashboard': typeof AppTeacherDashboardRoute
  '/teachers': typeof AppTeachersRouteWithChildren
  '/timetable': typeof AppTimetableRoute
  '/students/$studentId': typeof AppStudentsStudentIdRoute
  '/teachers/$teacherId': typeof AppTeachersTeacherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/communications': typeof AppCommunicationsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/fees': typeof AppFeesRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/parent-dashboard': typeof AppParentDashboardRoute
  '/_app/parents': typeof AppParentsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRouteWithChildren
  '/_app/subjects': typeof AppSubjectsRoute
  '/_app/teacher-dashboard': typeof AppTeacherDashboardRoute
  '/_app/teachers': typeof AppTeachersRouteWithChildren
  '/_app/timetable': typeof AppTimetableRoute
  '/_app/students/$studentId': typeof AppStudentsStudentIdRoute
  '/_app/teachers/$teacherId': typeof AppTeachersTeacherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reset-password'
    | '/ai-assistant'
    | '/attendance'
    | '/calendar'
    | '/classes'
    | '/communications'
    | '/dashboard'
    | '/expenses'
    | '/fees'
    | '/library'
    | '/notifications'
    | '/parent-dashboard'
    | '/parents'
    | '/reports'
    | '/results'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/teacher-dashboard'
    | '/teachers'
    | '/timetable'
    | '/students/$studentId'
    | '/teachers/$teacherId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reset-password'
    | '/ai-assistant'
    | '/attendance'
    | '/calendar'
    | '/classes'
    | '/communications'
    | '/dashboard'
    | '/expenses'
    | '/fees'
    | '/library'
    | '/notifications'
    | '/parent-dashboard'
    | '/parents'
    | '/reports'
    | '/results'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/teacher-dashboard'
    | '/teachers'
    | '/timetable'
    | '/students/$studentId'
    | '/teachers/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/reset-password'
    | '/_app/ai-assistant'
    | '/_app/attendance'
    | '/_app/calendar'
    | '/_app/classes'
    | '/_app/communications'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/fees'
    | '/_app/library'
    | '/_app/notifications'
    | '/_app/parent-dashboard'
    | '/_app/parents'
    | '/_app/reports'
    | '/_app/results'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/subjects'
    | '/_app/teacher-dashboard'
    | '/_app/teachers'
    | '/_app/timetable'
    | '/_app/students/$studentId'
    | '/_app/teachers/$teacherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/timetable': {
      id: '/_app/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AppTimetableRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher-dashboard': {
      id: '/_app/teacher-dashboard'
      path: '/teacher-dashboard'
      fullPath: '/teacher-dashboard'
      preLoaderRoute: typeof AppTeacherDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects': {
      id: '/_app/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parents': {
      id: '/_app/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof AppParentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent-dashboard': {
      id: '/_app/parent-dashboard'
      path: '/parent-dashboard'
      fullPath: '/parent-dashboard'
      preLoaderRoute: typeof AppParentDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fees': {
      id: '/_app/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AppFeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communications': {
      id: '/_app/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof AppCommunicationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers/$teacherId': {
      id: '/_app/teachers/$teacherId'
      path: '/$teacherId'
      fullPath: '/teachers/$teacherId'
      preLoaderRoute: typeof AppTeachersTeacherIdRouteImport
      parentRoute: typeof AppTeachersRoute
    }
    '/_app/students/$studentId': {
      id: '/_app/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof AppStudentsStudentIdRouteImport
      parentRoute: typeof AppStudentsRoute
    }
  }
}

interface AppStudentsRouteChildren {
  AppStudentsStudentIdRoute: typeof AppStudentsStudentIdRoute
}

const AppStudentsRouteChildren: AppStudentsRouteChildren = {
  AppStudentsStudentIdRoute: AppStudentsStudentIdRoute,
}

const AppStudentsRouteWithChildren = AppStudentsRoute._addFileChildren(
  AppStudentsRouteChildren,
)

interface AppTeachersRouteChildren {
  AppTeachersTeacherIdRoute: typeof AppTeachersTeacherIdRoute
}

const AppTeachersRouteChildren: AppTeachersRouteChildren = {
  AppTeachersTeacherIdRoute: AppTeachersTeacherIdRoute,
}

const AppTeachersRouteWithChildren = AppTeachersRoute._addFileChildren(
  AppTeachersRouteChildren,
)

interface AppRouteChildren {
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppClassesRoute: typeof AppClassesRoute
  AppCommunicationsRoute: typeof AppCommunicationsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppFeesRoute: typeof AppFeesRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppParentDashboardRoute: typeof AppParentDashboardRoute
  AppParentsRoute: typeof AppParentsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRouteWithChildren
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppTeacherDashboardRoute: typeof AppTeacherDashboardRoute
  AppTeachersRoute: typeof AppTeachersRouteWithChildren
  AppTimetableRoute: typeof AppTimetableRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppClassesRoute: AppClassesRoute,
  AppCommunicationsRoute: AppCommunicationsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppFeesRoute: AppFeesRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppParentDashboardRoute: AppParentDashboardRoute,
  AppParentsRoute: AppParentsRoute,
  AppReportsRoute: AppReportsRoute,
  AppResultsRoute: AppResultsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRouteWithChildren,
  AppSubjectsRoute: AppSubjectsRoute,
  AppTeacherDashboardRoute: AppTeacherDashboardRoute,
  AppTeachersRoute: AppTeachersRouteWithChildren,
  AppTimetableRoute: AppTimetableRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
